### ISSUE TITLE
Build fails due to invalid GLUON_TARGET "sunxi"

### ISSUE THREAD

**Issue by Sprinterfreak** [ffrgb/site-ffrgb#19]
`make FORCE_UNSAFE_CONFIGURE=1 GLUON_GIT_REF=v2018.2 GLUON_RELEASE=v2018.2.x`
fails with
> Please set GLUON_TARGET to a valid target. Gluon supports the following targets:
>  * ar71xx-generic
>  * ar71xx-tiny
>  * ar71xx-nand
>  * brcm2708-bcm2708
>  * brcm2708-bcm2709
>  * mpc85xx-generic
>  * ramips-mt7621
>  * sunxi-cortexa7
>  * x86-generic
>  * x86-geode
>  * x86-64
>  * ipq40xx
>  * ramips-mt7620
>  * ramips-mt76x8
>  * ramips-rt305x
>  * ar71xx-mikrotik
>  * brcm2708-bcm2710
>  * ipq806x
>  * mvebu-cortexa9
> Makefile:124: recipe for target 'config' failed
> make[2]: *** [config] Error 1
> make[2]: Leaving directory '/root/site-ffrgb/gluon-build'
> Makefile:51: recipe for target 'build' failed
> make[1]: *** [build] Error 2
> make[1]: Leaving directory '/root/site-ffrgb'
> Makefile:40: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by Sprinterfreak** [comment]
According to [Gluon 2018.2 - documentation](https://gluon.readthedocs.io/en/v2018.2.x/releases/v2018.2.html?highlight=sunxi)
target sunxi got renamed to sunxi-cortexa7
ToDo: Change Makefile

**Comment by lephisto** [comment]
fixiert :)
